Update session.md
beego/beedoc pull request #843
Opened 2020-05-09 11:41 UTC by TalLannder

2020-12-07 00:44 UTC, flycash reviewed
can be used like??

2021-01-01 00:11 UTC, codysnider requested changes

2021-01-01 00:11 UTC, codysnider commented on en-US/mvc/controller/session.md
> +After being switched on, session can used be used like this:
```suggestion
After being switched on, session can be used like this:
```

2021-01-01 14:06 UTC, flycash approved these changes

2021-01-01 14:06 UTC, merged